USE [master]
GO

/****** Object:  Database [members_db]    Script Date: 7/11/2017 9:55:35 PM ******/
CREATE DATABASE [members_db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'members_db', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\members_db.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'members_db_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\members_db_log.ldf' , SIZE = 1040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [members_db] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [members_db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [members_db] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [members_db] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [members_db] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [members_db] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [members_db] SET ARITHABORT OFF 
GO

ALTER DATABASE [members_db] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [members_db] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [members_db] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [members_db] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [members_db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [members_db] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [members_db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [members_db] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [members_db] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [members_db] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [members_db] SET  ENABLE_BROKER 
GO

ALTER DATABASE [members_db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [members_db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [members_db] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [members_db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [members_db] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [members_db] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [members_db] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [members_db] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [members_db] SET  MULTI_USER 
GO

ALTER DATABASE [members_db] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [members_db] SET DB_CHAINING OFF 
GO

ALTER DATABASE [members_db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [members_db] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [members_db] SET  READ_WRITE 
GO

