//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlLibraryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.BorrowedBies = new HashSet<BorrowedBy>();
        }
    
        public int BookId { get; set; }
        public string BookName { get; set; }
        public string AuthorName { get; set; }
        public string PublisherName { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> PurchasedDate { get; set; }
        public string PurchasedBillNo { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> NoOfCopies { get; set; }
        public Nullable<decimal> FinePerDay { get; set; }
        public string BookImage { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<BorrowedBy> BorrowedBies { get; set; }
    }
}
