//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlLibraryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowedBy
    {
        public int BorrowedId { get; set; }
        public int MemberId { get; set; }
        public int BookId { get; set; }
        public string BorrowedDate { get; set; }
        public string ReturnDate { get; set; }
        public decimal CurrentFine { get; set; }
        public byte returned { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
